### ISSUE TITLE
App not working after restart - docker-compose

### ISSUE THREAD

**Issue by joekerna** [standardnotes/syncing-server#68]
I've successfully started the syncing server using `docker-compose up -d`.

After a reboot the docker image `syncing-server_app` keeps restarting

> 7fb5acb2882d        syncing-server_app                     "bash -c 'bundle exe…"   2 days ago          Restarting (1) 2 seconds ago                                                           syncing-server_app_1
> 75eb82f6285f         mysql:5.7                              "docker-entrypoint.s…"   2 days ago          Up 13 minutes                  3306/tcp, 33060/tcp                                     syncing-server_db_1

Only a manual stop using `docker-compose down` followed by a restart `docker-compose up -d` will start the app again

**Comment by karolsojko** [comment]
@joekerna can you update to latest `develop` branch and check if it works now? Please remember to rebuild the image with `docker-compose build` before starting the server

**Comment by joekerna** [comment]
Awesome! Thank you,

it's working now

**Comment by joekerna** [comment]
However I can't login to this server using the Mac App and the Android App anymore. I get

> This version of the application does not support your newer account type. Please upgrade to the latest version of Standard Notes to sign in.

**Comment by baptiste-grob** [comment]
This happens if you've upgraded the encryption of your account to our newer (in development) protocol, of if you registered on a new version of the client, in which case you're automatically on the new account type.
What client did you create your account from?

**Comment by joekerna** [comment]
I've registered with an older version a couple of months back.

Does the new development syncing server not work with the released clients (Mac/Android)?

**Comment by karolsojko** [comment]
@joekerna we're working on a new version in the `develop` branch - please use the stable `master` branch if you want to reffer to the code that's in production (compatible with the released clients).

As this issue does not relate any longer to docker-compose can we close it ?

**Comment by joekerna** [comment]
Alright. I'll go back to the `master` branch and live with the reboot issue for now knowing that it'll be fixed eventually.

Thanks!

**Comment by joekerna** [comment]
But now even with the `master` branch syncing server I can't log any more using the Android App

> Oops
> This version of the application does not support your newer account type. Please upgrade to the latest version of Standard Notes to sign in.

**Comment by mobitar** [comment]
@joekerna looking at your database, can you check what your `user.version` field is equal to?

**Comment by mobitar** [comment]
Also when you said "it's working now", which client was that with? Are there certain clients that allow you to login but others that don't?

**Comment by joekerna** [comment]
With that I meant that I can reboot the server and the app will restart without a loop. I hadn't tried to actually log into the app.
I just checked the 

> Hi! You're not supposed to be here. 

message

**Comment by mobitar** [comment]
What about your user.version, can you check what it is?

**Comment by joekerna** [comment]
Where can I find that? I've searched my MySQL Dump but can't find it.

**Comment by johnny243** [comment]
You can execute the following query in your database:

``` SQL
SELECT version FROM users WHERE email = 'your-email-address';
```

---

Also, you can use the `rails console`:

`User.find_by_email('your-email-address')` will return the user with all fields, including the `version`.

**Comment by joekerna** [comment]
I'm sorry, I had to revert back to the `master` branch to be able to login again.
I guess there is no use in doing it on this version, is there?!

**Comment by mobitar** [comment]
So the error "This version of the application does not support your newer account type. Please upgrade to the latest version of Standard Notes to sign in." occurs if you try to sign in **to an account that does not exist** on a v3.3.x client using the develop branch of the syncing server. The reason is, in general, when you try to sign in to an account that doesn't exist, the server will not tell you "this account doesn't exist." Instead, it will send you back "pseudo" parameters for the non-existent account, to conceal information regarding the fact that this account doesn't exist. These sudo parameters will return the latest version of the syncing protocol specification, which on the develop branch of the syncing server is `004`. However, v3.3.x clients only support up to `003` of the protocol specification. Thus the error you're seeing.

It's important to note that when using the docker setup and the default .env values, you will be setting up a totally different database than if you set up your own MySQL server locally. So an account you created pre-Docker will "no longer exist" with the Docker setup.

To solve this, you'd need to allow your Docker container to access your system's pre-existing MySQL server. However I'm not sure the best way to go about this, so I'll leave that to @karolsojko.
